# Form implementation generated from reading ui file 'AnalLocalBuckling.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_LocalBuckling_Dialog(object):
    def setupUi(self, LocalBuckling_Dialog):
        LocalBuckling_Dialog.setObjectName("LocalBuckling_Dialog")
        LocalBuckling_Dialog.resize(417, 431)
        LocalBuckling_Dialog.setMinimumSize(QtCore.QSize(417, 431))
        LocalBuckling_Dialog.setMaximumSize(QtCore.QSize(417, 431))
        LocalBuckling_Dialog.setStyleSheet("*{\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"Segoe UI\";\n"
"background-color: rgb(43, 43, 43);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1 px solid;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(144, 200, 246);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1 px solid;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        LocalBuckling_Dialog.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LocalBuckling_Dialog)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(LocalBuckling_Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_2.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(25, 4, 4, 6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FEM_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.FEM_radioButton.setEnabled(True)
        self.FEM_radioButton.setObjectName("FEM_radioButton")
        self.horizontalLayout_2.addWidget(self.FEM_radioButton)
        self.FSM_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.FSM_radioButton.setObjectName("FSM_radioButton")
        self.horizontalLayout_2.addWidget(self.FSM_radioButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_9 = QtWidgets.QGroupBox(LocalBuckling_Dialog)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 49))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 49))
        self.groupBox_9.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_3.setContentsMargins(25, 4, 4, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PrinAxis_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.PrinAxis_radioButton.setChecked(True)
        self.PrinAxis_radioButton.setObjectName("PrinAxis_radioButton")
        self.horizontalLayout_3.addWidget(self.PrinAxis_radioButton)
        self.GeoAxis_radioButton = QtWidgets.QRadioButton(self.groupBox_9)
        self.GeoAxis_radioButton.setObjectName("GeoAxis_radioButton")
        self.horizontalLayout_3.addWidget(self.GeoAxis_radioButton)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_4 = QtWidgets.QGroupBox(LocalBuckling_Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 131))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 131))
        self.groupBox_4.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(27, 6, 0, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, 2, 4, 2)
        self.gridLayout_2.setHorizontalSpacing(220)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Px_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.Px_lineEdit.setMinimumSize(QtCore.QSize(70, 21))
        self.Px_lineEdit.setMaximumSize(QtCore.QSize(70, 21))
        self.Px_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.Px_lineEdit.setObjectName("Px_lineEdit")
        self.gridLayout_2.addWidget(self.Px_lineEdit, 0, 1, 1, 1)
        self.Mz_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.Mz_lineEdit.setMinimumSize(QtCore.QSize(70, 21))
        self.Mz_lineEdit.setMaximumSize(QtCore.QSize(70, 21))
        self.Mz_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.Mz_lineEdit.setObjectName("Mz_lineEdit")
        self.gridLayout_2.addWidget(self.Mz_lineEdit, 2, 1, 1, 1)
        self.My_lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.My_lineEdit.setMinimumSize(QtCore.QSize(70, 21))
        self.My_lineEdit.setMaximumSize(QtCore.QSize(70, 21))
        self.My_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.My_lineEdit.setObjectName("My_lineEdit")
        self.gridLayout_2.addWidget(self.My_lineEdit, 1, 1, 1, 1)
        self.My_label = QtWidgets.QLabel(self.groupBox_4)
        self.My_label.setMinimumSize(QtCore.QSize(80, 21))
        self.My_label.setMaximumSize(QtCore.QSize(80, 21))
        self.My_label.setObjectName("My_label")
        self.gridLayout_2.addWidget(self.My_label, 1, 0, 1, 1)
        self.Px_label = QtWidgets.QLabel(self.groupBox_4)
        self.Px_label.setObjectName("Px_label")
        self.gridLayout_2.addWidget(self.Px_label, 0, 0, 1, 1)
        self.Mz_label = QtWidgets.QLabel(self.groupBox_4)
        self.Mz_label.setMinimumSize(QtCore.QSize(80, 21))
        self.Mz_label.setMaximumSize(QtCore.QSize(80, 21))
        self.Mz_label.setObjectName("Mz_label")
        self.gridLayout_2.addWidget(self.Mz_label, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(LocalBuckling_Dialog)
        self.groupBox_3.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(27, 6, 2, 6)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 2, 4, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMinimumSize(QtCore.QSize(80, 20))
        self.label.setMaximumSize(QtCore.QSize(80, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Max_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Max_radioButton.setMinimumSize(QtCore.QSize(135, 20))
        self.Max_radioButton.setMaximumSize(QtCore.QSize(135, 20))
        self.Max_radioButton.setObjectName("Max_radioButton")
        self.gridLayout.addWidget(self.Max_radioButton, 0, 3, 1, 1)
        self.Height_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Height_radioButton.setMinimumSize(QtCore.QSize(60, 20))
        self.Height_radioButton.setMaximumSize(QtCore.QSize(60, 20))
        self.Height_radioButton.setObjectName("Height_radioButton")
        self.gridLayout.addWidget(self.Height_radioButton, 0, 2, 1, 1)
        self.Width_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.Width_radioButton.setMinimumSize(QtCore.QSize(60, 20))
        self.Width_radioButton.setMaximumSize(QtCore.QSize(60, 20))
        self.Width_radioButton.setObjectName("Width_radioButton")
        self.gridLayout.addWidget(self.Width_radioButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(2, 4, 6, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ModesNum_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.ModesNum_lineEdit.setMinimumSize(QtCore.QSize(70, 21))
        self.ModesNum_lineEdit.setMaximumSize(QtCore.QSize(70, 21))
        self.ModesNum_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.ModesNum_lineEdit.setObjectName("ModesNum_lineEdit")
        self.gridLayout_3.addWidget(self.ModesNum_lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 4, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setMaximumSize(QtCore.QSize(50, 20))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.LengthTimes_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.LengthTimes_lineEdit.setMinimumSize(QtCore.QSize(35, 21))
        self.LengthTimes_lineEdit.setMaximumSize(QtCore.QSize(35, 21))
        self.LengthTimes_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.LengthTimes_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LengthTimes_lineEdit.setObjectName("LengthTimes_lineEdit")
        self.horizontalLayout_6.addWidget(self.LengthTimes_lineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.GenerateMesh_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.GenerateMesh_pushButton.setMinimumSize(QtCore.QSize(100, 18))
        self.GenerateMesh_pushButton.setMaximumSize(QtCore.QSize(100, 18))
        self.GenerateMesh_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::disabled{color:rgb(153, 153, 153)}\n"
"QPushButton{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.GenerateMesh_pushButton.setObjectName("GenerateMesh_pushButton")
        self.horizontalLayout_6.addWidget(self.GenerateMesh_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 4, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setMaximumSize(QtCore.QSize(160, 20))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.MeshSize_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.MeshSize_lineEdit.setMinimumSize(QtCore.QSize(35, 21))
        self.MeshSize_lineEdit.setMaximumSize(QtCore.QSize(35, 21))
        self.MeshSize_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.MeshSize_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MeshSize_lineEdit.setObjectName("MeshSize_lineEdit")
        self.horizontalLayout_7.addWidget(self.MeshSize_lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.ClearMesh_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.ClearMesh_pushButton.setMinimumSize(QtCore.QSize(100, 18))
        self.ClearMesh_pushButton.setMaximumSize(QtCore.QSize(100, 18))
        self.ClearMesh_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::disabled{color:rgb(153, 153, 153)}\n"
"QPushButton{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.ClearMesh_pushButton.setObjectName("ClearMesh_pushButton")
        self.horizontalLayout_7.addWidget(self.ClearMesh_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(LocalBuckling_Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 32))
        self.groupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ShowMesh_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.ShowMesh_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.ShowMesh_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.ShowMesh_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::disabled{color:rgb(153, 153, 153)}\n"
"QPushButton{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.ShowMesh_pushButton.setObjectName("ShowMesh_pushButton")
        self.horizontalLayout.addWidget(self.ShowMesh_pushButton)
        self.ShowResults_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.ShowResults_pushButton.setMinimumSize(QtCore.QSize(85, 23))
        self.ShowResults_pushButton.setMaximumSize(QtCore.QSize(85, 23))
        self.ShowResults_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::disabled{color:rgb(153, 153, 153)}\n"
"QPushButton{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.ShowResults_pushButton.setObjectName("ShowResults_pushButton")
        self.horizontalLayout.addWidget(self.ShowResults_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Run_pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Run_pushButton.sizePolicy().hasHeightForWidth())
        self.Run_pushButton.setSizePolicy(sizePolicy)
        self.Run_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.Run_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.Run_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::disabled{color:rgb(153, 153, 153)}\n"
"QPushButton{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.Run_pushButton.setObjectName("Run_pushButton")
        self.horizontalLayout.addWidget(self.Run_pushButton)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.Cancel_pushButton.setSizePolicy(sizePolicy)
        self.Cancel_pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.Cancel_pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.Cancel_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.horizontalLayout.addWidget(self.Cancel_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(LocalBuckling_Dialog)
        QtCore.QMetaObject.connectSlotsByName(LocalBuckling_Dialog)
        LocalBuckling_Dialog.setTabOrder(self.FEM_radioButton, self.FSM_radioButton)
        LocalBuckling_Dialog.setTabOrder(self.FSM_radioButton, self.PrinAxis_radioButton)
        LocalBuckling_Dialog.setTabOrder(self.PrinAxis_radioButton, self.GeoAxis_radioButton)
        LocalBuckling_Dialog.setTabOrder(self.GeoAxis_radioButton, self.Px_lineEdit)
        LocalBuckling_Dialog.setTabOrder(self.Px_lineEdit, self.My_lineEdit)
        LocalBuckling_Dialog.setTabOrder(self.My_lineEdit, self.Mz_lineEdit)
        LocalBuckling_Dialog.setTabOrder(self.Mz_lineEdit, self.Width_radioButton)
        LocalBuckling_Dialog.setTabOrder(self.Width_radioButton, self.Height_radioButton)
        LocalBuckling_Dialog.setTabOrder(self.Height_radioButton, self.Max_radioButton)
        LocalBuckling_Dialog.setTabOrder(self.Max_radioButton, self.ModesNum_lineEdit)
        LocalBuckling_Dialog.setTabOrder(self.ModesNum_lineEdit, self.LengthTimes_lineEdit)
        LocalBuckling_Dialog.setTabOrder(self.LengthTimes_lineEdit, self.MeshSize_lineEdit)
        LocalBuckling_Dialog.setTabOrder(self.MeshSize_lineEdit, self.ShowMesh_pushButton)
        LocalBuckling_Dialog.setTabOrder(self.ShowMesh_pushButton, self.ShowResults_pushButton)
        LocalBuckling_Dialog.setTabOrder(self.ShowResults_pushButton, self.Run_pushButton)
        LocalBuckling_Dialog.setTabOrder(self.Run_pushButton, self.Cancel_pushButton)

    def retranslateUi(self, LocalBuckling_Dialog):
        _translate = QtCore.QCoreApplication.translate
        LocalBuckling_Dialog.setWindowTitle(_translate("LocalBuckling_Dialog", "Caculation of Local Buckling"))
        self.groupBox_2.setTitle(_translate("LocalBuckling_Dialog", "Analysis Method"))
        self.FEM_radioButton.setText(_translate("LocalBuckling_Dialog", "Finite Element Method"))
        self.FSM_radioButton.setText(_translate("LocalBuckling_Dialog", "Finite Strip Method"))
        self.groupBox_9.setTitle(_translate("LocalBuckling_Dialog", "Axis Settings"))
        self.PrinAxis_radioButton.setText(_translate("LocalBuckling_Dialog", "Principal Axis"))
        self.GeoAxis_radioButton.setText(_translate("LocalBuckling_Dialog", "Geometric Axis"))
        self.groupBox_4.setTitle(_translate("LocalBuckling_Dialog", "Loading Conditions"))
        self.My_label.setText(_translate("LocalBuckling_Dialog", "Moment (My) :"))
        self.Px_label.setText(_translate("LocalBuckling_Dialog", "Axial Load (P) :"))
        self.Mz_label.setText(_translate("LocalBuckling_Dialog", "Moment (Mz) :"))
        self.label_8.setText(_translate("LocalBuckling_Dialog", "Notes: Axial Load: Compression (+); Tension: Negative (-);"))
        self.groupBox_3.setTitle(_translate("LocalBuckling_Dialog", "Analysis Parameters"))
        self.label.setText(_translate("LocalBuckling_Dialog", "Unit Length:"))
        self.Max_radioButton.setText(_translate("LocalBuckling_Dialog", "Max (Width, Height)"))
        self.Height_radioButton.setText(_translate("LocalBuckling_Dialog", "Height"))
        self.Width_radioButton.setText(_translate("LocalBuckling_Dialog", "Width"))
        self.label_2.setText(_translate("LocalBuckling_Dialog", "Num of Modes:"))
        self.label_4.setText(_translate("LocalBuckling_Dialog", "Length: "))
        self.label_5.setText(_translate("LocalBuckling_Dialog", "Times of Unit Length"))
        self.GenerateMesh_pushButton.setText(_translate("LocalBuckling_Dialog", "Generate Mesh"))
        self.label_6.setText(_translate("LocalBuckling_Dialog", "Mesh Size:  Unit Length /"))
        self.ClearMesh_pushButton.setText(_translate("LocalBuckling_Dialog", "Clear Mesh"))
        self.ShowMesh_pushButton.setText(_translate("LocalBuckling_Dialog", "Show Mesh"))
        self.ShowResults_pushButton.setText(_translate("LocalBuckling_Dialog", "Show Results"))
        self.Run_pushButton.setText(_translate("LocalBuckling_Dialog", "Run"))
        self.Cancel_pushButton.setText(_translate("LocalBuckling_Dialog", "Cancel"))
