# Form implementation generated from reading ui file 'BoxGirdert.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_BoxGirder_Dialog(object):
    def setupUi(self, BoxGirder_Dialog):
        BoxGirder_Dialog.setObjectName("BoxGirder_Dialog")
        BoxGirder_Dialog.resize(540, 533)
        BoxGirder_Dialog.setMinimumSize(QtCore.QSize(540, 529))
        BoxGirder_Dialog.setMaximumSize(QtCore.QSize(540, 533))
        BoxGirder_Dialog.setStyleSheet("*{    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Segoe UI\";\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(BoxGirder_Dialog)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 2, 1, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(BoxGirder_Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui/Template/Box Girder.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(1, 0, 0, -1)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ModelingType_groupBox = QtWidgets.QGroupBox(BoxGirder_Dialog)
        self.ModelingType_groupBox.setStyleSheet("background-color: rgb(158, 158, 158);")
        self.ModelingType_groupBox.setObjectName("ModelingType_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ModelingType_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Centerline_radioButton = QtWidgets.QRadioButton(self.ModelingType_groupBox)
        self.Centerline_radioButton.setObjectName("Centerline_radioButton")
        self.verticalLayout.addWidget(self.Centerline_radioButton)
        self.Outline_radioButton = QtWidgets.QRadioButton(self.ModelingType_groupBox)
        self.Outline_radioButton.setEnabled(False)
        self.Outline_radioButton.setObjectName("Outline_radioButton")
        self.verticalLayout.addWidget(self.Outline_radioButton)
        self.verticalLayout_2.addWidget(self.ModelingType_groupBox)
        self.Dimension_groupBox = QtWidgets.QGroupBox(BoxGirder_Dialog)
        self.Dimension_groupBox.setStyleSheet("background-color: rgb(158, 158, 158);")
        self.Dimension_groupBox.setObjectName("Dimension_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Dimension_groupBox)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(6, 4, 6, -1)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(4)
        self.formLayout.setObjectName("formLayout")
        self.B_label = QtWidgets.QLabel(self.Dimension_groupBox)
        self.B_label.setObjectName("B_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.B_label)
        self.B1_inputlineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.B1_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.B1_inputlineEdit.setObjectName("B1_inputlineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.B1_inputlineEdit)
        self.tw_label = QtWidgets.QLabel(self.Dimension_groupBox)
        self.tw_label.setObjectName("tw_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.tw_label)
        self.B2_inputlineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.B2_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.B2_inputlineEdit.setObjectName("B2_inputlineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.B2_inputlineEdit)
        self.D1_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.D1_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.D1_lineEdit.setObjectName("D1_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.D1_lineEdit)
        self.D2_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.D2_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.D2_lineEdit.setObjectName("D2_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.D2_lineEdit)
        self.tf_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.tf_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tf_lineEdit.setObjectName("tf_lineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tf_lineEdit)
        self.tw1_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.tw1_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tw1_lineEdit.setObjectName("tw1_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tw1_lineEdit)
        self.tw2_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.tw2_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tw2_lineEdit.setObjectName("tw2_lineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tw2_lineEdit)
        self.tw3_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.tw3_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tw3_lineEdit.setObjectName("tw3_lineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tw3_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.D3_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.D3_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.D3_lineEdit.setObjectName("D3_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.D3_lineEdit)
        self.D4_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.D4_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.D4_lineEdit.setObjectName("D4_lineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.D4_lineEdit)
        self.label_8 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.Dimension_groupBox)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.IShape_groupBox = QtWidgets.QGroupBox(BoxGirder_Dialog)
        self.IShape_groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.IShape_groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(160, 160, 160);")
        self.IShape_groupBox.setObjectName("IShape_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.IShape_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.G_label = QtWidgets.QLabel(self.IShape_groupBox)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 4, 1, 1)
        self.ID_label = QtWidgets.QLabel(self.IShape_groupBox)
        self.ID_label.setObjectName("ID_label")
        self.gridLayout.addWidget(self.ID_label, 0, 0, 1, 1)
        self.E_label = QtWidgets.QLabel(self.IShape_groupBox)
        self.E_label.setObjectName("E_label")
        self.gridLayout.addWidget(self.E_label, 0, 2, 1, 1)
        self.fy_label = QtWidgets.QLabel(self.IShape_groupBox)
        self.fy_label.setObjectName("fy_label")
        self.gridLayout.addWidget(self.fy_label, 1, 2, 1, 1)
        self.Color_label = QtWidgets.QLabel(self.IShape_groupBox)
        self.Color_label.setObjectName("Color_label")
        self.gridLayout.addWidget(self.Color_label, 1, 0, 1, 1)
        self.eu_inputlineEdit = QtWidgets.QLineEdit(self.IShape_groupBox)
        self.eu_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.eu_inputlineEdit.setObjectName("eu_inputlineEdit")
        self.gridLayout.addWidget(self.eu_inputlineEdit, 1, 5, 1, 1)
        self.fy_inputlineEdit = QtWidgets.QLineEdit(self.IShape_groupBox)
        self.fy_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.fy_inputlineEdit.setObjectName("fy_inputlineEdit")
        self.gridLayout.addWidget(self.fy_inputlineEdit, 1, 3, 1, 1)
        self.eu_label = QtWidgets.QLabel(self.IShape_groupBox)
        self.eu_label.setObjectName("eu_label")
        self.gridLayout.addWidget(self.eu_label, 1, 4, 1, 1)
        self.G_inputlineEdit = QtWidgets.QLineEdit(self.IShape_groupBox)
        self.G_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.G_inputlineEdit.setObjectName("G_inputlineEdit")
        self.gridLayout.addWidget(self.G_inputlineEdit, 1, 1, 1, 1)
        self.E_inputlineEdit = QtWidgets.QLineEdit(self.IShape_groupBox)
        self.E_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.E_inputlineEdit.setObjectName("E_inputlineEdit")
        self.gridLayout.addWidget(self.E_inputlineEdit, 0, 5, 1, 1)
        self.ID_inputlineEdit = QtWidgets.QLineEdit(self.IShape_groupBox)
        self.ID_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.ID_inputlineEdit.setObjectName("ID_inputlineEdit")
        self.gridLayout.addWidget(self.ID_inputlineEdit, 0, 3, 1, 1)
        self.ColorButton = QtWidgets.QPushButton(self.IShape_groupBox)
        self.ColorButton.setStyleSheet("*{    \n"
"    border:1px solid rgb(0,0,0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"")
        self.ColorButton.setText("")
        self.ColorButton.setObjectName("ColorButton")
        self.gridLayout.addWidget(self.ColorButton, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.IShape_groupBox, 0, 0, 1, 1)
        self.button_GroupBox = QtWidgets.QGroupBox(BoxGirder_Dialog)
        self.button_GroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.button_GroupBox.setStyleSheet("background-color: rgb(160, 160, 160);")
        self.button_GroupBox.setObjectName("button_GroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.button_GroupBox)
        self.horizontalLayout_3.setContentsMargins(0, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.OK_button = QtWidgets.QPushButton(self.button_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK_button.sizePolicy().hasHeightForWidth())
        self.OK_button.setSizePolicy(sizePolicy)
        self.OK_button.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.OK_button.setObjectName("OK_button")
        self.horizontalLayout_4.addWidget(self.OK_button)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.button_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.Cancel_pushButton.setSizePolicy(sizePolicy)
        self.Cancel_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.horizontalLayout_4.addWidget(self.Cancel_pushButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addWidget(self.button_GroupBox, 3, 0, 1, 1)

        self.retranslateUi(BoxGirder_Dialog)
        QtCore.QMetaObject.connectSlotsByName(BoxGirder_Dialog)
        BoxGirder_Dialog.setTabOrder(self.ID_inputlineEdit, self.E_inputlineEdit)
        BoxGirder_Dialog.setTabOrder(self.E_inputlineEdit, self.G_inputlineEdit)
        BoxGirder_Dialog.setTabOrder(self.G_inputlineEdit, self.fy_inputlineEdit)
        BoxGirder_Dialog.setTabOrder(self.fy_inputlineEdit, self.eu_inputlineEdit)
        BoxGirder_Dialog.setTabOrder(self.eu_inputlineEdit, self.Centerline_radioButton)
        BoxGirder_Dialog.setTabOrder(self.Centerline_radioButton, self.Outline_radioButton)
        BoxGirder_Dialog.setTabOrder(self.Outline_radioButton, self.B1_inputlineEdit)
        BoxGirder_Dialog.setTabOrder(self.B1_inputlineEdit, self.B2_inputlineEdit)
        BoxGirder_Dialog.setTabOrder(self.B2_inputlineEdit, self.D1_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.D1_lineEdit, self.D2_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.D2_lineEdit, self.D3_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.D3_lineEdit, self.D4_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.D4_lineEdit, self.tf_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.tf_lineEdit, self.tw1_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.tw1_lineEdit, self.tw2_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.tw2_lineEdit, self.tw3_lineEdit)
        BoxGirder_Dialog.setTabOrder(self.tw3_lineEdit, self.ColorButton)
        BoxGirder_Dialog.setTabOrder(self.ColorButton, self.OK_button)
        BoxGirder_Dialog.setTabOrder(self.OK_button, self.Cancel_pushButton)

    def retranslateUi(self, BoxGirder_Dialog):
        _translate = QtCore.QCoreApplication.translate
        BoxGirder_Dialog.setWindowTitle(_translate("BoxGirder_Dialog", "Box Girder - Template"))
        self.ModelingType_groupBox.setTitle(_translate("BoxGirder_Dialog", "Modeling Type"))
        self.Centerline_radioButton.setText(_translate("BoxGirder_Dialog", "Centerline"))
        self.Outline_radioButton.setText(_translate("BoxGirder_Dialog", "Outline"))
        self.Dimension_groupBox.setTitle(_translate("BoxGirder_Dialog", "Dimension"))
        self.B_label.setText(_translate("BoxGirder_Dialog", "B1 = "))
        self.tw_label.setText(_translate("BoxGirder_Dialog", "B2 = "))
        self.label_2.setText(_translate("BoxGirder_Dialog", "D1 = "))
        self.label_3.setText(_translate("BoxGirder_Dialog", "D2 = "))
        self.label_4.setText(_translate("BoxGirder_Dialog", "tf = "))
        self.label_5.setText(_translate("BoxGirder_Dialog", "tw1 = "))
        self.label_6.setText(_translate("BoxGirder_Dialog", "tw2 = "))
        self.label_7.setText(_translate("BoxGirder_Dialog", "tw3 = "))
        self.label_8.setText(_translate("BoxGirder_Dialog", "D3 ="))
        self.label_9.setText(_translate("BoxGirder_Dialog", "D4 = "))
        self.IShape_groupBox.setTitle(_translate("BoxGirder_Dialog", "Material"))
        self.G_label.setText(_translate("BoxGirder_Dialog", " E  = "))
        self.ID_label.setText(_translate("BoxGirder_Dialog", "Color = "))
        self.E_label.setText(_translate("BoxGirder_Dialog", "ID = "))
        self.fy_label.setText(_translate("BoxGirder_Dialog", "fy  = "))
        self.Color_label.setText(_translate("BoxGirder_Dialog", "     μ   = "))
        self.eu_label.setText(_translate("BoxGirder_Dialog", chr(949)+"u = "))
        self.OK_button.setText(_translate("BoxGirder_Dialog", "OK"))
        self.Cancel_pushButton.setText(_translate("BoxGirder_Dialog", "Cancel"))
