# Form implementation generated from reading ui file 'C:\Users\gaowl\PycharmProjects\Mastan3\Source\gui\msasect\ui\CalYSurfaceProgress.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_CalYSProgress(object):
    def setupUi(self, CalYSProgress):
        CalYSProgress.setObjectName("CalYSProgress")
        CalYSProgress.resize(300, 120)
        CalYSProgress.setMinimumSize(QtCore.QSize(300, 120))
        CalYSProgress.setMaximumSize(QtCore.QSize(300, 120))
        CalYSProgress.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(128, 128, 128);")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=CalYSProgress)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Info_textLabel = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.Info_textLabel.setObjectName("Info_textLabel")
        self.verticalLayout.addWidget(self.Info_textLabel)
        self.CalYS_progressBar = QtWidgets.QProgressBar(parent=self.verticalLayoutWidget)
        self.CalYS_progressBar.setProperty("value", 12)
        self.CalYS_progressBar.setObjectName("CalYS_progressBar")
        self.verticalLayout.addWidget(self.CalYS_progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OK_pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.OK_pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout.addWidget(self.OK_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CalYSProgress)
        QtCore.QMetaObject.connectSlotsByName(CalYSProgress)

    def retranslateUi(self, CalYSProgress):
        _translate = QtCore.QCoreApplication.translate
        CalYSProgress.setWindowTitle(_translate("CalYSProgress", "Calculate Yield Surfaces"))
        self.Info_textLabel.setText(_translate("CalYSProgress", "Start calculating..."))
        self.OK_pushButton.setText(_translate("CalYSProgress", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalYSProgress = QtWidgets.QWidget()
    ui = Ui_CalYSProgress()
    ui.setupUi(CalYSProgress)
    CalYSProgress.show()
    sys.exit(app.exec())
