# Form implementation generated from reading ui file 'GBAnalMessageBox.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from gui.msasect.base.OutputRedir import CallableEvent
from PySide6.QtWidgets import QTextBrowser


class CustomTextBrowser(QTextBrowser):
    def event(self, event):
        if isinstance(event, CallableEvent):
            event.execute()
            return True
        return super().event(event)


class Ui_GBAnalMessageBox_Dialog(object):
    def setupUi(self, GBAnalMessageBox_Dialog):
        GBAnalMessageBox_Dialog.setObjectName("GBAnalMessageBox_Dialog")
        GBAnalMessageBox_Dialog.resize(621, 548)
        GBAnalMessageBox_Dialog.setStyleSheet("QDialog\n"
"{\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"QComboBox\n"
"{\n"
"    border-radius: 3px;\n"
"}\n"
"QComboBox::hover\n"
"{\n"
"    background-color: rgb(244, 244, 244);\n"
"}\n"
"QComboBox::drop-down\n"
"{\n"
"    width: 20px;\n"
"    border-left: 1px solid rgb(192, 192, 192);\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow\n"
"{\n"
"    image:url(ui/ico/DownArrow.png);\n"
"    width: 10px;\n"
"}\n"
"QGroupBox\n"
"{\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLabel\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(144, 200, 246);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: rgb(160, 160, 160);\n"
"    color: rgb(80, 80, 80);\n"
"}\n"
"QTextBrowser\n"
"{\n"
"    background-color: rgb(43, 43, 43);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton\n"
"{\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QToolButton:hover\n"
"{\n"
"    background-color: rgba(255, 255, 255, 20%);\n"
"}\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: rgba(0, 0, 0, 20%);\n"
"    border-top: 1px solid rgba(0, 0, 0, 50%);\n"
"    border-left: 1px solid rgba(0, 0, 0, 50%);\n"
"    padding: 0;\n"
"}")
        GBAnalMessageBox_Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtWidgets.QGridLayout(GBAnalMessageBox_Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.MCMessageBox_textBrowser = CustomTextBrowser(GBAnalMessageBox_Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.MCMessageBox_textBrowser.setFont(font)
        self.MCMessageBox_textBrowser.setObjectName("MCMessageBox_textBrowser")
        self.gridLayout.addWidget(self.MCMessageBox_textBrowser, 1, 0, 2, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(GBAnalMessageBox_Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 34))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.STime_label = QtWidgets.QLabel(self.groupBox_4)
        self.STime_label.setMinimumSize(QtCore.QSize(80, 22))
        self.STime_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.STime_label.setIndent(1)
        self.STime_label.setObjectName("STime_label")
        self.horizontalLayout.addWidget(self.STime_label)
        self.StartTimeDay_label = QtWidgets.QLabel(self.groupBox_4)
        self.StartTimeDay_label.setMinimumSize(QtCore.QSize(70, 22))
        self.StartTimeDay_label.setText("")
        self.StartTimeDay_label.setObjectName("StartTimeDay_label")
        self.horizontalLayout.addWidget(self.StartTimeDay_label)
        self.StartTimer_label = QtWidgets.QLabel(self.groupBox_4)
        self.StartTimer_label.setMinimumSize(QtCore.QSize(70, 22))
        self.StartTimer_label.setText("")
        self.StartTimer_label.setObjectName("StartTimer_label")
        self.horizontalLayout.addWidget(self.StartTimer_label)
        spacerItem = QtWidgets.QSpacerItem(112, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Stop_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.Stop_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop_pushButton.sizePolicy().hasHeightForWidth())
        self.Stop_pushButton.setSizePolicy(sizePolicy)
        self.Stop_pushButton.setMinimumSize(QtCore.QSize(56, 22))
        self.Stop_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: rgb(160, 160, 160);\n"
"    color: rgb(80, 80, 80);\n"
"}")
        self.Stop_pushButton.setObjectName("Stop_pushButton")
        self.horizontalLayout.addWidget(self.Stop_pushButton)
        self.OK_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK_pushButton.sizePolicy().hasHeightForWidth())
        self.OK_pushButton.setSizePolicy(sizePolicy)
        self.OK_pushButton.setMinimumSize(QtCore.QSize(56, 22))
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.horizontalLayout.addWidget(self.OK_pushButton)
        self.gridLayout.addWidget(self.groupBox_4, 3, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(GBAnalMessageBox_Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 34))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ExportMessage_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExportMessage_label.sizePolicy().hasHeightForWidth())
        self.ExportMessage_label.setSizePolicy(sizePolicy)
        self.ExportMessage_label.setMinimumSize(QtCore.QSize(80, 22))
        self.ExportMessage_label.setMaximumSize(QtCore.QSize(160000, 16777215))
        self.ExportMessage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ExportMessage_label.setIndent(1)
        self.ExportMessage_label.setObjectName("ExportMessage_label")
        self.horizontalLayout_2.addWidget(self.ExportMessage_label)
        self.ExportFileFormat_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.ExportFileFormat_comboBox.setMinimumSize(QtCore.QSize(0, 22))
        self.ExportFileFormat_comboBox.setObjectName("ExportFileFormat_comboBox")
        self.ExportFileFormat_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.ExportFileFormat_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.SaveText_toolButton = QtWidgets.QToolButton(self.groupBox)
        self.SaveText_toolButton.setMinimumSize(QtCore.QSize(0, 22))
        self.SaveText_toolButton.setText("")
        self.SaveText_toolButton.setObjectName("SaveText_toolButton")
        self.horizontalLayout_2.addWidget(self.SaveText_toolButton)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 14)

        self.retranslateUi(GBAnalMessageBox_Dialog)
        QtCore.QMetaObject.connectSlotsByName(GBAnalMessageBox_Dialog)

    def retranslateUi(self, GBAnalMessageBox_Dialog):
        _translate = QtCore.QCoreApplication.translate
        GBAnalMessageBox_Dialog.setWindowTitle(_translate("GBAnalMessageBox_Dialog", "Analysis is running, please wait patiently ..."))
        self.STime_label.setText(_translate("GBAnalMessageBox_Dialog", "Start Time："))
        self.Stop_pushButton.setText(_translate("GBAnalMessageBox_Dialog", "Stop"))
        self.OK_pushButton.setText(_translate("GBAnalMessageBox_Dialog", "OK"))
        self.ExportMessage_label.setText(_translate("GBAnalMessageBox_Dialog", "Export message to:"))
        self.ExportFileFormat_comboBox.setItemText(0, _translate("GBAnalMessageBox_Dialog", "Text File Format"))
