# Form implementation generated from reading ui file 'HollowCircle.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_HollowCircle_Dialog(object):
    def setupUi(self, HollowCircle_Dialog):
        HollowCircle_Dialog.setObjectName("HollowCircle_Dialog")
        HollowCircle_Dialog.resize(540, 533)
        HollowCircle_Dialog.setMinimumSize(QtCore.QSize(540, 533))
        HollowCircle_Dialog.setMaximumSize(QtCore.QSize(540, 533))
        HollowCircle_Dialog.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        HollowCircle_Dialog.setStyleSheet("*{    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Segoe UI\";\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"")
        self.gridLayout_3 = QtWidgets.QGridLayout(HollowCircle_Dialog)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 2, 1, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(HollowCircle_Dialog)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("t3.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ModelingType_groupBox = QtWidgets.QGroupBox(HollowCircle_Dialog)
        self.ModelingType_groupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.ModelingType_groupBox.setObjectName("ModelingType_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ModelingType_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Centerline_radioButton = QtWidgets.QRadioButton(self.ModelingType_groupBox)
        self.Centerline_radioButton.setObjectName("Centerline_radioButton")
        self.verticalLayout.addWidget(self.Centerline_radioButton)
        self.Outline_radioButton = QtWidgets.QRadioButton(self.ModelingType_groupBox)
        self.Outline_radioButton.setEnabled(True)
        self.Outline_radioButton.setObjectName("Outline_radioButton")
        self.verticalLayout.addWidget(self.Outline_radioButton)
        self.verticalLayout_2.addWidget(self.ModelingType_groupBox)
        self.Dimension_groupBox = QtWidgets.QGroupBox(HollowCircle_Dialog)
        self.Dimension_groupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.Dimension_groupBox.setObjectName("Dimension_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Dimension_groupBox)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 6, 4)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.B_label = QtWidgets.QLabel(self.Dimension_groupBox)
        self.B_label.setMinimumSize(QtCore.QSize(0, 0))
        self.B_label.setObjectName("B_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.B_label)
        self.B_inputlineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.B_inputlineEdit.setMinimumSize(QtCore.QSize(78, 22))
        self.B_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.B_inputlineEdit.setObjectName("B_inputlineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.B_inputlineEdit)
        self.D_label = QtWidgets.QLabel(self.Dimension_groupBox)
        self.D_label.setMinimumSize(QtCore.QSize(0, 0))
        self.D_label.setObjectName("D_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.D_label)
        self.D_inputlineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.D_inputlineEdit.setMinimumSize(QtCore.QSize(78, 0))
        self.D_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.D_inputlineEdit.setObjectName("D_inputlineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.D_inputlineEdit)
        self.tf_label = QtWidgets.QLabel(self.Dimension_groupBox)
        self.tf_label.setObjectName("tf_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.tf_label)
        self.tw_inputlineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.tw_inputlineEdit.setMinimumSize(QtCore.QSize(78, 0))
        self.tw_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.tw_inputlineEdit.setObjectName("tw_inputlineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tw_inputlineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.Dimension_groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.Num_lineEdit = QtWidgets.QLineEdit(self.Dimension_groupBox)
        self.Num_lineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Num_lineEdit.setObjectName("Num_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Num_lineEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_2.addWidget(self.Dimension_groupBox)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.HollowCircle_groupBox = QtWidgets.QGroupBox(HollowCircle_Dialog)
        self.HollowCircle_groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.HollowCircle_groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(128, 128, 128);")
        self.HollowCircle_groupBox.setObjectName("HollowCircle_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.HollowCircle_groupBox)
        self.gridLayout_2.setContentsMargins(9, 2, 9, 2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(2, 2, 2, 4)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.G_label = QtWidgets.QLabel(self.HollowCircle_groupBox)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 4, 1, 1)
        self.ID_label = QtWidgets.QLabel(self.HollowCircle_groupBox)
        self.ID_label.setObjectName("ID_label")
        self.gridLayout.addWidget(self.ID_label, 0, 0, 1, 1)
        self.E_label = QtWidgets.QLabel(self.HollowCircle_groupBox)
        self.E_label.setObjectName("E_label")
        self.gridLayout.addWidget(self.E_label, 0, 2, 1, 1)
        self.fy_label = QtWidgets.QLabel(self.HollowCircle_groupBox)
        self.fy_label.setObjectName("fy_label")
        self.gridLayout.addWidget(self.fy_label, 1, 2, 1, 1)
        self.Color_label = QtWidgets.QLabel(self.HollowCircle_groupBox)
        self.Color_label.setObjectName("Color_label")
        self.gridLayout.addWidget(self.Color_label, 1, 0, 1, 1)
        self.eu_inputlineEdit = QtWidgets.QLineEdit(self.HollowCircle_groupBox)
        self.eu_inputlineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.eu_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.eu_inputlineEdit.setObjectName("eu_inputlineEdit")
        self.gridLayout.addWidget(self.eu_inputlineEdit, 1, 5, 1, 1)
        self.fy_inputlineEdit = QtWidgets.QLineEdit(self.HollowCircle_groupBox)
        self.fy_inputlineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.fy_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.fy_inputlineEdit.setObjectName("fy_inputlineEdit")
        self.gridLayout.addWidget(self.fy_inputlineEdit, 1, 3, 1, 1)
        self.eu_label = QtWidgets.QLabel(self.HollowCircle_groupBox)
        self.eu_label.setObjectName("eu_label")
        self.gridLayout.addWidget(self.eu_label, 1, 4, 1, 1)
        self.G_inputlineEdit = QtWidgets.QLineEdit(self.HollowCircle_groupBox)
        self.G_inputlineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.G_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.G_inputlineEdit.setObjectName("G_inputlineEdit")
        self.gridLayout.addWidget(self.G_inputlineEdit, 1, 1, 1, 1)
        self.E_inputlineEdit = QtWidgets.QLineEdit(self.HollowCircle_groupBox)
        self.E_inputlineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.E_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.E_inputlineEdit.setObjectName("E_inputlineEdit")
        self.gridLayout.addWidget(self.E_inputlineEdit, 0, 5, 1, 1)
        self.ID_inputlineEdit = QtWidgets.QLineEdit(self.HollowCircle_groupBox)
        self.ID_inputlineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.ID_inputlineEdit.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.ID_inputlineEdit.setObjectName("ID_inputlineEdit")
        self.gridLayout.addWidget(self.ID_inputlineEdit, 0, 3, 1, 1)
        self.ColorButton = QtWidgets.QPushButton(self.HollowCircle_groupBox)
        self.ColorButton.setMinimumSize(QtCore.QSize(0, 19))
        self.ColorButton.setStyleSheet("*{    \n"
"    border:1px solid rgb(0,0,0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"")
        self.ColorButton.setText("")
        self.ColorButton.setObjectName("ColorButton")
        self.gridLayout.addWidget(self.ColorButton, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.HollowCircle_groupBox, 0, 0, 1, 1)
        self.button_GroupBox = QtWidgets.QGroupBox(HollowCircle_Dialog)
        self.button_GroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.button_GroupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.button_GroupBox.setObjectName("button_GroupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.button_GroupBox)
        self.horizontalLayout_3.setContentsMargins(0, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(2, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Import_pushButton = QtWidgets.QPushButton(self.button_GroupBox)
        self.Import_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Import_pushButton.setObjectName("Import_pushButton")
        self.horizontalLayout_4.addWidget(self.Import_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.OK_button = QtWidgets.QPushButton(self.button_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OK_button.sizePolicy().hasHeightForWidth())
        self.OK_button.setSizePolicy(sizePolicy)
        self.OK_button.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.OK_button.setObjectName("OK_button")
        self.horizontalLayout_4.addWidget(self.OK_button)
        self.Cancel_pushButton = QtWidgets.QPushButton(self.button_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.Cancel_pushButton.setSizePolicy(sizePolicy)
        self.Cancel_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.horizontalLayout_4.addWidget(self.Cancel_pushButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addWidget(self.button_GroupBox, 3, 0, 1, 1)

        self.retranslateUi(HollowCircle_Dialog)
        QtCore.QMetaObject.connectSlotsByName(HollowCircle_Dialog)
        HollowCircle_Dialog.setTabOrder(self.ID_inputlineEdit, self.E_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.E_inputlineEdit, self.G_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.G_inputlineEdit, self.fy_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.fy_inputlineEdit, self.eu_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.eu_inputlineEdit, self.Centerline_radioButton)
        HollowCircle_Dialog.setTabOrder(self.Centerline_radioButton, self.Outline_radioButton)
        HollowCircle_Dialog.setTabOrder(self.Outline_radioButton, self.B_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.B_inputlineEdit, self.D_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.D_inputlineEdit, self.tw_inputlineEdit)
        HollowCircle_Dialog.setTabOrder(self.tw_inputlineEdit, self.Num_lineEdit)
        HollowCircle_Dialog.setTabOrder(self.Num_lineEdit, self.Import_pushButton)
        HollowCircle_Dialog.setTabOrder(self.Import_pushButton, self.ColorButton)
        HollowCircle_Dialog.setTabOrder(self.ColorButton, self.OK_button)
        HollowCircle_Dialog.setTabOrder(self.OK_button, self.Cancel_pushButton)

    def retranslateUi(self, HollowCircle_Dialog):
        _translate = QtCore.QCoreApplication.translate
        HollowCircle_Dialog.setWindowTitle(_translate("HollowCircle_Dialog", "Hollow Circle - Template"))
        self.ModelingType_groupBox.setTitle(_translate("HollowCircle_Dialog", "Modeling Type"))
        self.Centerline_radioButton.setText(_translate("HollowCircle_Dialog", "Centerline"))
        self.Outline_radioButton.setText(_translate("HollowCircle_Dialog", "Outline"))
        self.Dimension_groupBox.setTitle(_translate("HollowCircle_Dialog", "Dimension"))
        self.B_label.setText(_translate("HollowCircle_Dialog", "B = "))
        self.D_label.setText(_translate("HollowCircle_Dialog", "D = "))
        self.tf_label.setText(_translate("HollowCircle_Dialog", "tw = "))
        self.label_2.setText(_translate("HollowCircle_Dialog", "n Num. ="))
        self.HollowCircle_groupBox.setTitle(_translate("HollowCircle_Dialog", "Material"))
        self.G_label.setText(_translate("HollowCircle_Dialog", " E  = "))
        self.ID_label.setText(_translate("HollowCircle_Dialog", "Color = "))
        self.E_label.setText(_translate("HollowCircle_Dialog", "ID = "))
        self.fy_label.setText(_translate("HollowCircle_Dialog", "fy  = "))
        self.Color_label.setText(_translate("HollowCircle_Dialog", "     μ   = "))
        self.eu_label.setText(_translate("HollowCircle_Dialog", "eu = "))
        self.Import_pushButton.setText(_translate("HollowCircle_Dialog", "Import"))
        self.OK_button.setText(_translate("HollowCircle_Dialog", "OK"))
        self.Cancel_pushButton.setText(_translate("HollowCircle_Dialog", "Cancel"))
