# Form implementation generated from reading ui file 'MaterialAdd.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MatAddDialog(object):
    def setupUi(self, MatAddDialog):
        MatAddDialog.setObjectName("MatAddDialog")
        MatAddDialog.resize(335, 416)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MatAddDialog.sizePolicy().hasHeightForWidth())
        MatAddDialog.setSizePolicy(sizePolicy)
        MatAddDialog.setMinimumSize(QtCore.QSize(335, 416))
        MatAddDialog.setMaximumSize(QtCore.QSize(335, 416))
        MatAddDialog.setStyleSheet("*{    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Segoe UI\";\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(MatAddDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(MatAddDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(331, 176))
        self.groupBox.setMaximumSize(QtCore.QSize(331, 1760))
        self.groupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout.setContentsMargins(4, 10, 2, 10)
        self.gridLayout.setHorizontalSpacing(32)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.MatIDInput = QtWidgets.QLineEdit(self.groupBox)
        self.MatIDInput.setMinimumSize(QtCore.QSize(0, 22))
        self.MatIDInput.setMaximumSize(QtCore.QSize(124, 22))
        self.MatIDInput.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.MatIDInput.setObjectName("MatIDInput")
        self.gridLayout.addWidget(self.MatIDInput, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 8, 1, 1, 1)
        self.E_Input = QtWidgets.QLineEdit(self.groupBox)
        self.E_Input.setMinimumSize(QtCore.QSize(0, 22))
        self.E_Input.setMaximumSize(QtCore.QSize(124, 22))
        self.E_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.E_Input.setObjectName("E_Input")
        self.gridLayout.addWidget(self.E_Input, 1, 1, 1, 1)
        self.Mu_Input = QtWidgets.QLineEdit(self.groupBox)
        self.Mu_Input.setMinimumSize(QtCore.QSize(0, 22))
        self.Mu_Input.setMaximumSize(QtCore.QSize(124, 22))
        self.Mu_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Mu_Input.setObjectName("Mu_Input")
        self.gridLayout.addWidget(self.Mu_Input, 2, 1, 1, 1)
        self.MatID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.MatID_Label.setFont(font)
        self.MatID_Label.setObjectName("MatID_Label")
        self.gridLayout.addWidget(self.MatID_Label, 2, 0, 1, 1)
        self.E_end_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.E_end_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.E_end_lineEdit.setObjectName("E_end_lineEdit")
        self.gridLayout.addWidget(self.E_end_lineEdit, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.PointIID_label = QtWidgets.QLabel(self.groupBox)
        self.PointIID_label.setObjectName("PointIID_label")
        self.gridLayout.addWidget(self.PointIID_label, 3, 0, 1, 1)
        self.eu_input = QtWidgets.QLineEdit(self.groupBox)
        self.eu_input.setMinimumSize(QtCore.QSize(0, 22))
        self.eu_input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.eu_input.setObjectName("eu_input")
        self.gridLayout.addWidget(self.eu_input, 4, 1, 1, 1)
        self.OutlineID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.OutlineID_Label.setFont(font)
        self.OutlineID_Label.setObjectName("OutlineID_Label")
        self.gridLayout.addWidget(self.OutlineID_Label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(169, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.E_begin_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.E_begin_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.E_begin_lineEdit.setObjectName("E_begin_lineEdit")
        self.gridLayout.addWidget(self.E_begin_lineEdit, 5, 1, 1, 1)
        self.Gra_law_label = QtWidgets.QLabel(self.groupBox)
        self.Gra_law_label.setObjectName("Gra_law_label")
        self.gridLayout.addWidget(self.Gra_law_label, 8, 0, 1, 1)
        self.Gra_ang_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.Gra_ang_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Gra_ang_lineEdit.setObjectName("Gra_ang_lineEdit")
        self.gridLayout.addWidget(self.Gra_ang_lineEdit, 7, 1, 1, 1)
        self.fy_Input = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fy_Input.sizePolicy().hasHeightForWidth())
        self.fy_Input.setSizePolicy(sizePolicy)
        self.fy_Input.setMinimumSize(QtCore.QSize(0, 22))
        self.fy_Input.setMaximumSize(QtCore.QSize(124, 22))
        self.fy_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.fy_Input.setObjectName("fy_Input")
        self.gridLayout.addWidget(self.fy_Input, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.k_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.k_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.k_lineEdit.setObjectName("k_lineEdit")
        self.gridLayout.addWidget(self.k_lineEdit, 9, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.DirType_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.DirType_comboBox.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.DirType_comboBox.setObjectName("DirType_comboBox")
        self.DirType_comboBox.addItem("")
        self.DirType_comboBox.addItem("")
        self.gridLayout.addWidget(self.DirType_comboBox, 10, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(MatAddDialog)
        self.groupBox_2.setMaximumSize(QtCore.QSize(2080, 34))
        self.groupBox_2.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(4, 2, 0, 2)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Import_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.Import_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Import_pushButton.setObjectName("Import_pushButton")
        self.horizontalLayout.addWidget(self.Import_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.MaterialAdd_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.MaterialAdd_pushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.MaterialAdd_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.MaterialAdd_pushButton.setObjectName("MaterialAdd_pushButton")
        self.horizontalLayout.addWidget(self.MaterialAdd_pushButton)
        self.MatchAddCancel_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.MatchAddCancel_pushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.MatchAddCancel_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.MatchAddCancel_pushButton.setObjectName("MatchAddCancel_pushButton")
        self.horizontalLayout.addWidget(self.MatchAddCancel_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(MatAddDialog)
        QtCore.QMetaObject.connectSlotsByName(MatAddDialog)
        MatAddDialog.setTabOrder(self.MatIDInput, self.E_Input)
        MatAddDialog.setTabOrder(self.E_Input, self.Mu_Input)
        MatAddDialog.setTabOrder(self.Mu_Input, self.fy_Input)
        MatAddDialog.setTabOrder(self.fy_Input, self.eu_input)
        MatAddDialog.setTabOrder(self.eu_input, self.E_begin_lineEdit)
        MatAddDialog.setTabOrder(self.E_begin_lineEdit, self.E_end_lineEdit)
        MatAddDialog.setTabOrder(self.E_end_lineEdit, self.Gra_ang_lineEdit)
        MatAddDialog.setTabOrder(self.Gra_ang_lineEdit, self.comboBox)
        MatAddDialog.setTabOrder(self.comboBox, self.k_lineEdit)
        MatAddDialog.setTabOrder(self.k_lineEdit, self.DirType_comboBox)
        MatAddDialog.setTabOrder(self.DirType_comboBox, self.Import_pushButton)
        MatAddDialog.setTabOrder(self.Import_pushButton, self.MaterialAdd_pushButton)
        MatAddDialog.setTabOrder(self.MaterialAdd_pushButton, self.MatchAddCancel_pushButton)

    def retranslateUi(self, MatAddDialog):
        _translate = QtCore.QCoreApplication.translate
        MatAddDialog.setWindowTitle(_translate("MatAddDialog", "Add Material"))
        self.comboBox.setItemText(0, _translate("MatAddDialog", "Power law"))
        self.comboBox.setItemText(1, _translate("MatAddDialog", "Exponential law"))
        self.comboBox.setItemText(2, _translate("MatAddDialog", "Sigmoid law"))
        self.MatID_Label.setText(_translate("MatAddDialog", "Poisson\'s Ratio, μ:"))
        self.label_2.setText(_translate("MatAddDialog", "Maximum Tensile Strain, eu:"))
        self.PointIID_label.setText(_translate("MatAddDialog", "Characteristic Strength, fy:"))
        self.OutlineID_Label.setText(_translate("MatAddDialog", "Young\'s Modulus of Elasticity, E:"))
        self.label_4.setText(_translate("MatAddDialog", "E_end:"))
        self.label.setText(_translate("MatAddDialog", "Material ID:"))
        self.label_5.setText(_translate("MatAddDialog", "Gra_ang:"))
        self.label_3.setText(_translate("MatAddDialog", "E_begin:"))
        self.Gra_law_label.setText(_translate("MatAddDialog", "Gra_law:"))
        self.label_7.setText(_translate("MatAddDialog", "k:"))
        self.label_6.setText(_translate("MatAddDialog", "Direction Type:"))
        self.DirType_comboBox.setItemText(0, _translate("MatAddDialog", "Single direction"))
        self.DirType_comboBox.setItemText(1, _translate("MatAddDialog", "Radial"))
        self.Import_pushButton.setText(_translate("MatAddDialog", "Import"))
        self.MaterialAdd_pushButton.setText(_translate("MatAddDialog", "OK"))
        self.MatchAddCancel_pushButton.setText(_translate("MatAddDialog", "Cancel"))
