# Form implementation generated from reading ui file 'OutlineAdd.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_OutlineAdd_Dialog(object):
    def setupUi(self, OutlineAdd_Dialog):
        OutlineAdd_Dialog.setObjectName("OutlineAdd_Dialog")
        OutlineAdd_Dialog.resize(212, 225)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OutlineAdd_Dialog.sizePolicy().hasHeightForWidth())
        OutlineAdd_Dialog.setSizePolicy(sizePolicy)
        OutlineAdd_Dialog.setMinimumSize(QtCore.QSize(212, 225))
        OutlineAdd_Dialog.setMaximumSize(QtCore.QSize(2120, 225))
        OutlineAdd_Dialog.setStyleSheet("*{    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Segoe UI\";\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(OutlineAdd_Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(OutlineAdd_Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(208, 185))
        self.groupBox.setMaximumSize(QtCore.QSize(2080, 185))
        self.groupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.formLayout.setContentsMargins(2, 2, 2, 0)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.GroupID_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.GroupID_lineEdit.setMinimumSize(QtCore.QSize(124, 22))
        self.GroupID_lineEdit.setMaximumSize(QtCore.QSize(1240, 22))
        self.GroupID_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.GroupID_lineEdit.setObjectName("GroupID_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.GroupID_lineEdit)
        self.OutlineID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.OutlineID_Label.setFont(font)
        self.OutlineID_Label.setObjectName("OutlineID_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.OutlineID_Label)
        self.LoopID_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.LoopID_lineEdit.setMinimumSize(QtCore.QSize(124, 22))
        self.LoopID_lineEdit.setMaximumSize(QtCore.QSize(1240, 22))
        self.LoopID_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.LoopID_lineEdit.setObjectName("LoopID_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LoopID_lineEdit)
        self.MatID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.MatID_Label.setFont(font)
        self.MatID_Label.setObjectName("MatID_Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.MatID_Label)
        self.MatID_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.MatID_lineEdit.setMinimumSize(QtCore.QSize(124, 22))
        self.MatID_lineEdit.setMaximumSize(QtCore.QSize(1240, 22))
        self.MatID_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.MatID_lineEdit.setObjectName("MatID_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.MatID_lineEdit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Type_label = QtWidgets.QLabel(self.groupBox)
        self.Type_label.setObjectName("Type_label")
        self.horizontalLayout_2.addWidget(self.Type_label)
        self.Solid_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.Solid_radioButton.setObjectName("Solid_radioButton")
        self.horizontalLayout_2.addWidget(self.Solid_radioButton)
        self.Opening_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.Opening_radioButton.setObjectName("Opening_radioButton")
        self.horizontalLayout_2.addWidget(self.Opening_radioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.formLayout_2.setContentsMargins(2, 0, 2, 6)
        self.formLayout_2.setHorizontalSpacing(32)
        self.formLayout_2.setVerticalSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.PointIID_label = QtWidgets.QLabel(self.groupBox)
        self.PointIID_label.setObjectName("PointIID_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.PointIID_label)
        self.Points_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Points_lineEdit.sizePolicy().hasHeightForWidth())
        self.Points_lineEdit.setSizePolicy(sizePolicy)
        self.Points_lineEdit.setMinimumSize(QtCore.QSize(124, 22))
        self.Points_lineEdit.setMaximumSize(QtCore.QSize(1240, 22))
        self.Points_lineEdit.setStyleSheet("*{    \n"
"    font: 10pt \"Times New Roman\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Points_lineEdit.setObjectName("Points_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Points_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(OutlineAdd_Dialog)
        self.groupBox_2.setMaximumSize(QtCore.QSize(2080, 34))
        self.groupBox_2.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.OutlineAdd_button = QtWidgets.QPushButton(self.groupBox_2)
        self.OutlineAdd_button.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.OutlineAdd_button.setObjectName("OutlineAdd_button")
        self.horizontalLayout.addWidget(self.OutlineAdd_button)
        self.OutlineAddCancel_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.OutlineAddCancel_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.OutlineAddCancel_pushButton.setObjectName("OutlineAddCancel_pushButton")
        self.horizontalLayout.addWidget(self.OutlineAddCancel_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(OutlineAdd_Dialog)
        QtCore.QMetaObject.connectSlotsByName(OutlineAdd_Dialog)

    def retranslateUi(self, OutlineAdd_Dialog):
        _translate = QtCore.QCoreApplication.translate
        OutlineAdd_Dialog.setWindowTitle(_translate("OutlineAdd_Dialog", "Outline Add"))
        self.label.setText(_translate("OutlineAdd_Dialog", "Group ID :"))
        self.OutlineID_Label.setText(_translate("OutlineAdd_Dialog", "Loop ID :"))
        self.MatID_Label.setText(_translate("OutlineAdd_Dialog", "Mat. ID :"))
        self.Type_label.setText(_translate("OutlineAdd_Dialog", "Type:"))
        self.Solid_radioButton.setText(_translate("OutlineAdd_Dialog", "Solid"))
        self.Opening_radioButton.setText(_translate("OutlineAdd_Dialog", "Opening"))
        self.PointIID_label.setText(_translate("OutlineAdd_Dialog", "Points  :"))
        self.label_2.setText(_translate("OutlineAdd_Dialog", "(e.g. 1,2,3,4)"))
        self.OutlineAdd_button.setText(_translate("OutlineAdd_Dialog", "OK"))
        self.OutlineAddCancel_pushButton.setText(_translate("OutlineAdd_Dialog", "Cancel"))
