# Form implementation generated from reading ui file 'ShowResultsBuckling_LineElement.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_GlobalBucklingPlot_Dialog(object):
    def setupUi(self, GlobalBucklingPlot_Dialog):
        GlobalBucklingPlot_Dialog.setObjectName("GlobalBucklingPlot_Dialog")
        GlobalBucklingPlot_Dialog.resize(640, 627)
        GlobalBucklingPlot_Dialog.setMinimumSize(QtCore.QSize(640, 620))
        GlobalBucklingPlot_Dialog.setMaximumSize(QtCore.QSize(5000, 6700))
        GlobalBucklingPlot_Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Segoe UI\";\n"
"background-color: rgb(43, 43, 43);\n"
"\n"
"QPushButton::hover{background-color:rgb(144, 200, 246)}\n"
"\n"
"\n"
"\n"
"")
        GlobalBucklingPlot_Dialog.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GlobalBucklingPlot_Dialog)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(GlobalBucklingPlot_Dialog)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(4090, 1160))
        self.groupBox_6.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_12.setContentsMargins(2, 4, 2, 6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.Compression_Layout = QtWidgets.QVBoxLayout()
        self.Compression_Layout.setObjectName("Compression_Layout")
        self.verticalLayout_12.addLayout(self.Compression_Layout)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(GlobalBucklingPlot_Dialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 32))
        self.groupBox.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ExportResults_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.ExportResults_pushButton.setMinimumSize(QtCore.QSize(120, 24))
        self.ExportResults_pushButton.setMaximumSize(QtCore.QSize(120, 24))
        self.ExportResults_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.ExportResults_pushButton.setObjectName("ExportResults_pushButton")
        self.horizontalLayout.addWidget(self.ExportResults_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Close_pushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Close_pushButton.sizePolicy().hasHeightForWidth())
        self.Close_pushButton.setSizePolicy(sizePolicy)
        self.Close_pushButton.setMinimumSize(QtCore.QSize(75, 24))
        self.Close_pushButton.setMaximumSize(QtCore.QSize(75, 24))
        self.Close_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}")
        self.Close_pushButton.setObjectName("Close_pushButton")
        self.horizontalLayout.addWidget(self.Close_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(GlobalBucklingPlot_Dialog)
        QtCore.QMetaObject.connectSlotsByName(GlobalBucklingPlot_Dialog)
        GlobalBucklingPlot_Dialog.setTabOrder(self.ExportResults_pushButton, self.Close_pushButton)

    def retranslateUi(self, GlobalBucklingPlot_Dialog):
        _translate = QtCore.QCoreApplication.translate
        GlobalBucklingPlot_Dialog.setWindowTitle(_translate("GlobalBucklingPlot_Dialog", "Global Buckling Plot"))
        self.groupBox_6.setTitle(_translate("GlobalBucklingPlot_Dialog", "Global Buckling"))
        self.ExportResults_pushButton.setText(_translate("GlobalBucklingPlot_Dialog", "Export Curve Points"))
        self.Close_pushButton.setText(_translate("GlobalBucklingPlot_Dialog", "Close"))
