# Form implementation generated from reading ui file 'SegmentAdd.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_SegmentAdd_Dialog(object):
    def setupUi(self, SegmentAdd_Dialog):
        SegmentAdd_Dialog.setObjectName("SegmentAdd_Dialog")
        SegmentAdd_Dialog.resize(216, 209)
        SegmentAdd_Dialog.setMinimumSize(QtCore.QSize(216, 209))
        SegmentAdd_Dialog.setMaximumSize(QtCore.QSize(216, 209))
        SegmentAdd_Dialog.setStyleSheet("*{    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 9pt \"Segoe UI\";\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(SegmentAdd_Dialog)
        self.verticalLayout.setContentsMargins(2, 2, 2, 1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(SegmentAdd_Dialog)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(128, 128, 128);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 6, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(6, 2, 2, 6)
        self.formLayout.setHorizontalSpacing(32)
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.SegID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.SegID_Label.setFont(font)
        self.SegID_Label.setObjectName("SegID_Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.SegID_Label)
        self.SegIDInput = QtWidgets.QLineEdit(self.groupBox)
        self.SegIDInput.setMinimumSize(QtCore.QSize(0, 0))
        self.SegIDInput.setMaximumSize(QtCore.QSize(103, 22))
        self.SegIDInput.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SegIDInput.setObjectName("SegIDInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.SegIDInput)
        self.PointSID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.PointSID_Label.setFont(font)
        self.PointSID_Label.setObjectName("PointSID_Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.PointSID_Label)
        self.PointSID_Input = QtWidgets.QLineEdit(self.groupBox)
        self.PointSID_Input.setMinimumSize(QtCore.QSize(0, 0))
        self.PointSID_Input.setMaximumSize(QtCore.QSize(103, 22))
        self.PointSID_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.PointSID_Input.setObjectName("PointSID_Input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.PointSID_Input)
        self.PointEID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.PointEID_Label.setFont(font)
        self.PointEID_Label.setObjectName("PointEID_Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.PointEID_Label)
        self.PointEID_Input = QtWidgets.QLineEdit(self.groupBox)
        self.PointEID_Input.setMinimumSize(QtCore.QSize(0, 0))
        self.PointEID_Input.setMaximumSize(QtCore.QSize(103, 22))
        self.PointEID_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.PointEID_Input.setObjectName("PointEID_Input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.PointEID_Input)
        self.Thickness_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.Thickness_Label.setFont(font)
        self.Thickness_Label.setObjectName("Thickness_Label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Thickness_Label)
        self.Thk_Input = QtWidgets.QLineEdit(self.groupBox)
        self.Thk_Input.setMinimumSize(QtCore.QSize(0, 0))
        self.Thk_Input.setMaximumSize(QtCore.QSize(103, 22))
        self.Thk_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.Thk_Input.setObjectName("Thk_Input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Thk_Input)
        self.MatID_Label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.MatID_Label.setFont(font)
        self.MatID_Label.setObjectName("MatID_Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.MatID_Label)
        self.MatID_Input = QtWidgets.QLineEdit(self.groupBox)
        self.MatID_Input.setMinimumSize(QtCore.QSize(0, 0))
        self.MatID_Input.setMaximumSize(QtCore.QSize(103, 22))
        self.MatID_Input.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.MatID_Input.setObjectName("MatID_Input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.MatID_Input)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(SegmentAdd_Dialog)
        self.groupBox_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(128, 128, 128);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(2, 0, 2, 2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(2, 3, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.SegmentAdd_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SegmentAdd_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SegmentAdd_pushButton.setObjectName("SegmentAdd_pushButton")
        self.horizontalLayout.addWidget(self.SegmentAdd_pushButton)
        self.SegAddCancel_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.SegAddCancel_pushButton.setStyleSheet("*{    \n"
"    font: 9pt \"Segoe UI\";\n"
"    color: rgb(0, 0, 0);\n"
"    background: rgb(255, 255, 255);\n"
"}\n"
"")
        self.SegAddCancel_pushButton.setObjectName("SegAddCancel_pushButton")
        self.horizontalLayout.addWidget(self.SegAddCancel_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(SegmentAdd_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SegmentAdd_Dialog)
        SegmentAdd_Dialog.setTabOrder(self.SegIDInput, self.MatID_Input)
        SegmentAdd_Dialog.setTabOrder(self.MatID_Input, self.PointSID_Input)
        SegmentAdd_Dialog.setTabOrder(self.PointSID_Input, self.PointEID_Input)
        SegmentAdd_Dialog.setTabOrder(self.PointEID_Input, self.Thk_Input)
        SegmentAdd_Dialog.setTabOrder(self.Thk_Input, self.SegmentAdd_pushButton)
        SegmentAdd_Dialog.setTabOrder(self.SegmentAdd_pushButton, self.SegAddCancel_pushButton)

    def retranslateUi(self, SegmentAdd_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SegmentAdd_Dialog.setWindowTitle(_translate("SegmentAdd_Dialog", "Add Segment"))
        self.SegID_Label.setText(_translate("SegmentAdd_Dialog", "Segment ID:"))
        self.PointSID_Label.setText(_translate("SegmentAdd_Dialog", "Point I ID："))
        self.PointEID_Label.setText(_translate("SegmentAdd_Dialog", "Point J ID:"))
        self.Thickness_Label.setText(_translate("SegmentAdd_Dialog", "Thickness:"))
        self.MatID_Label.setText(_translate("SegmentAdd_Dialog", "Mat. ID:"))
        self.SegmentAdd_pushButton.setText(_translate("SegmentAdd_Dialog", "OK"))
        self.SegAddCancel_pushButton.setText(_translate("SegmentAdd_Dialog", "Cancel"))
