# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\BoundaryInput.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(215, 131)
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(12, 12, 55, 16))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 235, 23))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.formLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Ux = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.Ux.setObjectName("Ux")
        self.horizontalLayout.addWidget(self.Ux)
        self.Uy = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.Uy.setObjectName("Uy")
        self.horizontalLayout.addWidget(self.Uy)
        self.Uz = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.Uz.setObjectName("Uz")
        self.horizontalLayout.addWidget(self.Uz)
        self.NodeID = QtWidgets.QLineEdit(dialog)
        self.NodeID.setGeometry(QtCore.QRect(68, 10, 101, 21))
        self.NodeID.setObjectName("NodeID")
        self.OKButton = QtWidgets.QToolButton(dialog)
        self.OKButton.setGeometry(QtCore.QRect(124, 100, 81, 21))
        self.OKButton.setObjectName("OKButton")
        self.formLayoutWidget_2 = QtWidgets.QWidget(dialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 235, 23))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.formLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Rx = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.Rx.setObjectName("Rx")
        self.horizontalLayout_2.addWidget(self.Rx)
        self.Ry = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.Ry.setObjectName("Ry")
        self.horizontalLayout_2.addWidget(self.Ry)
        self.Rz = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.Rz.setObjectName("Rz")
        self.horizontalLayout_2.addWidget(self.Rz)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)
        dialog.setTabOrder(self.NodeID, self.Ux)
        dialog.setTabOrder(self.Ux, self.Uy)
        dialog.setTabOrder(self.Uy, self.Uz)
        dialog.setTabOrder(self.Uz, self.Rx)
        dialog.setTabOrder(self.Rx, self.Ry)
        dialog.setTabOrder(self.Ry, self.Rz)
        dialog.setTabOrder(self.Rz, self.OKButton)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Boundary"))
        self.label.setText(_translate("dialog", "Node ID:"))
        self.Ux.setText(_translate("dialog", "Ux"))
        self.Uy.setText(_translate("dialog", "Uy"))
        self.Uz.setText(_translate("dialog", "Uz"))
        self.OKButton.setText(_translate("dialog", "OK"))
        self.Rx.setText(_translate("dialog", "Rx"))
        self.Ry.setText(_translate("dialog", "Ry"))
        self.Rz.setText(_translate("dialog", "Rz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec())
