# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\LoadInput.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(191, 245)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 8, 72, 15))
        self.label.setObjectName("label")
        self.NodeID = QtWidgets.QLineEdit(Dialog)
        self.NodeID.setGeometry(QtCore.QRect(80, 8, 101, 21))
        self.NodeID.setObjectName("NodeID")
        self.OKButton = QtWidgets.QToolButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(100, 214, 81, 21))
        self.OKButton.setObjectName("OKButton")
        self.Mz = QtWidgets.QLineEdit(Dialog)
        self.Mz.setGeometry(QtCore.QRect(80, 188, 101, 21))
        self.Mz.setObjectName("Mz")
        self.My = QtWidgets.QLineEdit(Dialog)
        self.My.setGeometry(QtCore.QRect(80, 158, 101, 21))
        self.My.setObjectName("My")
        self.Mx = QtWidgets.QLineEdit(Dialog)
        self.Mx.setGeometry(QtCore.QRect(81, 128, 101, 21))
        self.Mx.setObjectName("Mx")
        self.Fz = QtWidgets.QLineEdit(Dialog)
        self.Fz.setGeometry(QtCore.QRect(81, 98, 101, 21))
        self.Fz.setObjectName("Fz")
        self.Fy = QtWidgets.QLineEdit(Dialog)
        self.Fy.setGeometry(QtCore.QRect(80, 68, 101, 21))
        self.Fy.setObjectName("Fy")
        self.Fx = QtWidgets.QLineEdit(Dialog)
        self.Fx.setGeometry(QtCore.QRect(80, 38, 101, 21))
        self.Fx.setObjectName("Fx")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(50, 38, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 68, 31, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(50, 98, 31, 21))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(50, 128, 31, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(50, 158, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(50, 188, 31, 21))
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.NodeID, self.Fx)
        Dialog.setTabOrder(self.Fx, self.Fy)
        Dialog.setTabOrder(self.Fy, self.Fz)
        Dialog.setTabOrder(self.Fz, self.Mx)
        Dialog.setTabOrder(self.Mx, self.My)
        Dialog.setTabOrder(self.My, self.Mz)
        Dialog.setTabOrder(self.Mz, self.OKButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Joint Load"))
        self.label.setText(_translate("Dialog", "Node ID:"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.label_4.setText(_translate("Dialog", "Fx:"))
        self.label_7.setText(_translate("Dialog", "Fy:"))
        self.label_8.setText(_translate("Dialog", "Fz:"))
        self.label_12.setText(_translate("Dialog", "Mx:"))
        self.label_13.setText(_translate("Dialog", "My:"))
        self.label_14.setText(_translate("Dialog", "Mz:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
