# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\MemInput.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(208, 154)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(12, 12, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(8, 40, 63, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(8, 70, 63, 16))
        self.label_3.setObjectName("label_3")
        self.MemID_Input = QtWidgets.QLineEdit(Dialog)
        self.MemID_Input.setGeometry(QtCore.QRect(84, 12, 113, 21))
        self.MemID_Input.setObjectName("MemID_Input")
        self.Node1ID_Input = QtWidgets.QLineEdit(Dialog)
        self.Node1ID_Input.setGeometry(QtCore.QRect(84, 40, 113, 21))
        self.Node1ID_Input.setObjectName("Node1ID_Input")
        self.Node2ID_Input = QtWidgets.QLineEdit(Dialog)
        self.Node2ID_Input.setGeometry(QtCore.QRect(84, 70, 113, 21))
        self.Node2ID_Input.setObjectName("Node2ID_Input")
        self.OKButton = QtWidgets.QToolButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(116, 126, 81, 21))
        self.OKButton.setObjectName("OKButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(12, 100, 71, 16))
        self.label_4.setObjectName("label_4")
        self.SectionID_Input = QtWidgets.QLineEdit(Dialog)
        self.SectionID_Input.setGeometry(QtCore.QRect(84, 100, 113, 21))
        self.SectionID_Input.setObjectName("SectionID_Input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.MemID_Input, self.Node1ID_Input)
        Dialog.setTabOrder(self.Node1ID_Input, self.Node2ID_Input)
        Dialog.setTabOrder(self.Node2ID_Input, self.SectionID_Input)
        Dialog.setTabOrder(self.SectionID_Input, self.OKButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Member"))
        self.label.setText(_translate("Dialog", "Member ID:"))
        self.label_2.setText(_translate("Dialog", " Node I ID:"))
        self.label_3.setText(_translate("Dialog", " Node J ID:"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.label_4.setText(_translate("Dialog", "Section ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
