# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\NodeInput.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(190, 149)
        self.x_coordinate = QtWidgets.QLineEdit(Dialog)
        self.x_coordinate.setGeometry(QtCore.QRect(68, 40, 113, 21))
        self.x_coordinate.setObjectName("x_coordinate")
        self.y_coordinate = QtWidgets.QLineEdit(Dialog)
        self.y_coordinate.setGeometry(QtCore.QRect(68, 68, 113, 21))
        self.y_coordinate.setObjectName("y_coordinate")
        self.z_coordinate = QtWidgets.QLineEdit(Dialog)
        self.z_coordinate.setGeometry(QtCore.QRect(68, 96, 113, 21))
        self.z_coordinate.setObjectName("z_coordinate")
        self.ID_Input = QtWidgets.QLineEdit(Dialog)
        self.ID_Input.setGeometry(QtCore.QRect(68, 12, 113, 21))
        self.ID_Input.setObjectName("ID_Input")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(12, 40, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(12, 12, 71, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(12, 68, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(12, 96, 16, 16))
        self.label_7.setObjectName("label_7")
        self.AcceptButton = QtWidgets.QToolButton(Dialog)
        self.AcceptButton.setGeometry(QtCore.QRect(100, 122, 81, 21))
        self.AcceptButton.setObjectName("AcceptButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.ID_Input, self.x_coordinate)
        Dialog.setTabOrder(self.x_coordinate, self.y_coordinate)
        Dialog.setTabOrder(self.y_coordinate, self.z_coordinate)
        Dialog.setTabOrder(self.z_coordinate, self.AcceptButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Node"))
        self.label_4.setText(_translate("Dialog", "x:"))
        self.label_5.setText(_translate("Dialog", "Node ID:"))
        self.label_6.setText(_translate("Dialog", "y:"))
        self.label_7.setText(_translate("Dialog", "z:"))
        self.AcceptButton.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
