# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\RunShow.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(268, 193)
        Dialog.setSizeGripEnabled(True)
        self.MaxIterationTime = QtWidgets.QLineEdit(Dialog)
        self.MaxIterationTime.setGeometry(QtCore.QRect(132, 132, 125, 21))
        self.MaxIterationTime.setObjectName("MaxIterationTime")
        self.LoadStep = QtWidgets.QLineEdit(Dialog)
        self.LoadStep.setGeometry(QtCore.QRect(132, 72, 125, 21))
        self.LoadStep.setObjectName("LoadStep")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(12, 12, 93, 16))
        self.label.setObjectName("label")
        self.ErrorTolerance = QtWidgets.QLineEdit(Dialog)
        self.ErrorTolerance.setGeometry(QtCore.QRect(132, 102, 125, 21))
        self.ErrorTolerance.setObjectName("ErrorTolerance")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(12, 102, 97, 21))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(12, 132, 123, 21))
        self.label_12.setObjectName("label_12")
        self.LoadFactor = QtWidgets.QLineEdit(Dialog)
        self.LoadFactor.setGeometry(QtCore.QRect(132, 42, 125, 21))
        self.LoadFactor.setObjectName("LoadFactor")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(12, 42, 77, 21))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(12, 72, 77, 21))
        self.label_7.setObjectName("label_7")
        self.OKButton = QtWidgets.QToolButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(86, 162, 81, 21))
        self.OKButton.setObjectName("OKButton")
        self.CancelButton = QtWidgets.QToolButton(Dialog)
        self.CancelButton.setGeometry(QtCore.QRect(176, 162, 81, 21))
        self.CancelButton.setObjectName("CancelButton")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(96, 12, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox, self.LoadFactor)
        Dialog.setTabOrder(self.LoadFactor, self.LoadStep)
        Dialog.setTabOrder(self.LoadStep, self.ErrorTolerance)
        Dialog.setTabOrder(self.ErrorTolerance, self.MaxIterationTime)
        Dialog.setTabOrder(self.MaxIterationTime, self.OKButton)
        Dialog.setTabOrder(self.OKButton, self.CancelButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Run"))
        self.MaxIterationTime.setText(_translate("Dialog", "99"))
        self.LoadStep.setText(_translate("Dialog", "1"))
        self.label.setText(_translate("Dialog", "Analysis type:"))
        self.ErrorTolerance.setText(_translate("Dialog", "0.001"))
        self.label_8.setText(_translate("Dialog", "Error Tolerance:"))
        self.label_12.setText(_translate("Dialog", "Max iteration time:"))
        self.LoadFactor.setText(_translate("Dialog", "1.0"))
        self.label_4.setText(_translate("Dialog", "Load Factor:"))
        self.label_7.setText(_translate("Dialog", "Load Step:"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        self.comboBox.setItemText(0, _translate("Dialog", "Static linear analysis"))
        self.comboBox.setItemText(1, _translate("Dialog", "Static nonlinear analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
