# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\SpringBoundaryInput.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(194, 245)
        Dialog.setSizeGripEnabled(True)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(48, 186, 31, 21))
        self.label_14.setObjectName("label_14")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(16, 10, 59, 16))
        self.label.setObjectName("label")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(48, 156, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(48, 96, 31, 21))
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(48, 36, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(48, 66, 31, 21))
        self.label_7.setObjectName("label_7")
        self.NodeID = QtWidgets.QLineEdit(Dialog)
        self.NodeID.setGeometry(QtCore.QRect(78, 6, 101, 21))
        self.NodeID.setObjectName("NodeID")
        self.OKButton = QtWidgets.QToolButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(98, 216, 81, 21))
        self.OKButton.setObjectName("OKButton")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(48, 126, 31, 21))
        self.label_12.setObjectName("label_12")
        self.comboBox_Ux = QtWidgets.QComboBox(Dialog)
        self.comboBox_Ux.setGeometry(QtCore.QRect(78, 36, 101, 22))
        self.comboBox_Ux.setObjectName("comboBox_Ux")
        self.comboBox_Uy = QtWidgets.QComboBox(Dialog)
        self.comboBox_Uy.setGeometry(QtCore.QRect(78, 66, 101, 22))
        self.comboBox_Uy.setObjectName("comboBox_Uy")
        self.comboBox_Uz = QtWidgets.QComboBox(Dialog)
        self.comboBox_Uz.setGeometry(QtCore.QRect(78, 96, 101, 22))
        self.comboBox_Uz.setObjectName("comboBox_Uz")
        self.comboBox_Rx = QtWidgets.QComboBox(Dialog)
        self.comboBox_Rx.setGeometry(QtCore.QRect(78, 126, 101, 22))
        self.comboBox_Rx.setObjectName("comboBox_Rx")
        self.comboBox_Ry = QtWidgets.QComboBox(Dialog)
        self.comboBox_Ry.setGeometry(QtCore.QRect(78, 156, 101, 22))
        self.comboBox_Ry.setObjectName("comboBox_Ry")
        self.comboBox_Rz = QtWidgets.QComboBox(Dialog)
        self.comboBox_Rz.setGeometry(QtCore.QRect(78, 184, 101, 22))
        self.comboBox_Rz.setObjectName("comboBox_Rz")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.NodeID, self.comboBox_Ux)
        Dialog.setTabOrder(self.comboBox_Ux, self.comboBox_Uy)
        Dialog.setTabOrder(self.comboBox_Uy, self.comboBox_Uz)
        Dialog.setTabOrder(self.comboBox_Uz, self.comboBox_Rx)
        Dialog.setTabOrder(self.comboBox_Rx, self.comboBox_Ry)
        Dialog.setTabOrder(self.comboBox_Ry, self.comboBox_Rz)
        Dialog.setTabOrder(self.comboBox_Rz, self.OKButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Spring Boundary"))
        self.label_14.setText(_translate("Dialog", "Rz:"))
        self.label.setText(_translate("Dialog", "Node ID:"))
        self.label_13.setText(_translate("Dialog", "Ry:"))
        self.label_8.setText(_translate("Dialog", "Uz:"))
        self.label_4.setText(_translate("Dialog", "Ux:"))
        self.label_7.setText(_translate("Dialog", "Uy:"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.label_12.setText(_translate("Dialog", "Rx:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
