# Form implementation generated from reading ui file 'F:\Mastan3\Mastan3\Source\gui\mastan\ui\SpingModelInput.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(243, 176)
        Dialog.setSizeGripEnabled(True)
        self.ID_Input = QtWidgets.QLineEdit(Dialog)
        self.ID_Input.setGeometry(QtCore.QRect(116, 16, 113, 21))
        self.ID_Input.setObjectName("ID_Input")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(12, 16, 105, 16))
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(116, 46, 113, 93))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.OKButton = QtWidgets.QToolButton(Dialog)
        self.OKButton.setGeometry(QtCore.QRect(148, 144, 81, 21))
        self.OKButton.setObjectName("OKButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(68, 42, 39, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(68, 60, 39, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(68, 82, 39, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(68, 100, 39, 25))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Spring Model"))
        self.label.setText(_translate("Dialog", "Spring Model ID:"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>F1 D1</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>F2 D2</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>...</p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>Fn Dn</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
